### ISSUE TITLE
Breaking change released as minor v4.30.0+ TF( provider 3.40.0 -> 3.41.0) [datadog_monitor]

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-datadog#641]
### Describe what happened

The upgrade of the provider to 3.41.0 https://github.com/pulumi/pulumi-datadog/pull/600 caused a breaking change in the 
datadog_monitor `priority` attribute has changed the type from Numer to String. 

This is not considered a breaking change for Terraform but it is a breaking change in typed languages https://developer.hashicorp.com/terraform/language/expressions/types#type-conversion 

All releases starting from [release v4.30.0](https://api.github.com/repos/pulumi/pulumi-datadog/releases/165939155) should IMO be v5. 

links: 

https://github.com/DataDog/terraform-provider-datadog/blob/master/CHANGELOG.md#features-2

https://github.com/DataDog/terraform-provider-datadog/pull/2455

https://github.com/DataDog/terraform-provider-datadog/compare/v3.40.0...v3.41.0

### Sample program

```typescript
new datadog.Monitor(
    "ecs-vm-total-memory-anomaly",
    {
      name: "ECS - Fargate service VM total memory anomaly",

      type: "query alert",
      query:
        "avg(last_4h):anomalies(avg:vm.memory.total{orchestrator:ecs} by {service,env}, 'basic', 2, direction='above', alert_window='last_1h', interval=60, count_default_zero='true') >= 1",

      message: lib.utils.trimMultilineString(`
      {{#is_alert}}
        The service "{{service.name}}" in the environment "{{env.name}}" ({{version.name}}) has an anormal VM total run queue length (io)
        ${getAlertTags(org, unit)}
      {{/is_alert}}
      {{#is_recovery}}
        The service "{{service.name}}" in the environment "{{env.name}}" ({{version.name}}) has recovered from the anomaly
        ${getRecoveryTags(org, unit)}
      {{/is_recovery}}
      `),

      includeTags: false,
      monitorThresholdWindows: {
        triggerWindow: "last_1h",
        recoveryWindow: "last_1h",
      },
      notifyNoData: true,
      priority: 4, // this is now string "4"
      renotifyInterval: 15,
      requireFullWindow: false,

      tags: ["pulumi", "ecs"],
      notifyAudit: false,
    },
  );
```

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Hi @1oglop1, thanks for opening the issue here. Pulumi providers don't bump major versions for every breaking change in the SDK, as that would make most versions a major version bump, which makes it meaningless. With 100s of resources most releases have at least one breaking change in the SDK.

We do major version bumps when the upstream TF provider makes a major version or for fairly major incompatible changes.
Pulumi minor versions are generally pulling in an upstream TF minor/patch version.
Pulumi patch versions should generally not contain any breaking changes - if it is important for your workflows, you might want to pin a minor version instead.
